exclude: [scss, config.rb, README.md, script.js, app.js, animation.js, transform.js, ease.js, zoomooz.js, modernizr-2.6.2.js, selectivizr.js, lte-ie8.js, ie9.js]
site_name: Greensboro Doctors | Health Care in Greensboro, NC | Eagle Physicians
tagline:
keywords: 
auto: true
css: css/global.css
